export const GET_FILMS_LOADING = 'GET_FILMS_LOADING';
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS';
export const GET_FILMS_FAIL = 'GET_FILMS_FAIL';

export const SEARCH_FILM_LOADING = 'SEARCH_FILM_LOADING';
export const SEARCH_FILM_SUCCESS= 'SEARCH_FILM_SUCCESS';
export const SEARCH_FILM_FAIL = 'SEARCH_FILM_FAIL';

export const DELETE_FILM_LOADING = 'DELETE_FILM_LOADING'
export const DELETE_FILM_SUCCESS = 'DELETE_FILM_SUCCESS'
export const DELETE_FILM_FAIL = 'DELETE_FILM_FAIL'

export const ADD_FILM_LOADING = 'ADD_FILM_LOADING';
export const ADD_FILM_SUCCESS = 'ADD_FILM_SUCCESS';
export const ADD_FILM_FAIL = 'ADD_FILM_FAIL';

export const FILTER_FILM_LOADING = 'FILTER_FILM_LOADING';
export const FILTER_FILM_SUCCESS = 'FILTER_FILM_SUCCESS';
export const FILTER_FILM_FAIL = 'FILTER_FILM_FAIL';